apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yana-chan-4k-state
  labels:
    app.kubernetes.io/name: yana-chan-4k
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
